CREATE TABLE `afv_script_asset_binding` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `project_id` bigint NOT NULL COMMENT '项目ID',
    `script_id` bigint NOT NULL COMMENT '剧本ID',
    `script_episode_id` bigint NOT NULL COMMENT '剧本分集ID',
    `episode_number` int DEFAULT NULL COMMENT '集号',
    `script_scene_item_id` bigint DEFAULT NULL COMMENT '剧本场次ID，分集预匹配阶段可为空',
    `asset_type` varchar(32) NOT NULL COMMENT '资产类型 character/scene/prop',
    `entity_name` varchar(255) NOT NULL COMMENT '剧本或资产中的实体名称',
    `entity_key` varchar(255) DEFAULT NULL COMMENT '场次 entityManifest key',
    `asset_id` bigint DEFAULT NULL COMMENT '匹配的主资产ID',
    `asset_item_id` bigint DEFAULT NULL COMMENT '匹配的子资产ID',
    `match_status` varchar(32) NOT NULL COMMENT 'matched/suggested/ambiguous/unmatched/ignored/missing_asset/uploaded_unused',
    `match_source` varchar(32) NOT NULL COMMENT 'exact_name/display_name/clean_name/alias/ai_selected/manual_selected/none',
    `confidence` int NOT NULL DEFAULT 0 COMMENT '匹配置信度 0-100',
    `evidence_text` varchar(512) DEFAULT NULL COMMENT '匹配证据文本',
    `candidate_json` json DEFAULT NULL COMMENT '候选资产列表',
    `reviewed` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否已确认',
    `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '逻辑删除',
    PRIMARY KEY (`id`),
    KEY `idx_script_asset_binding_episode` (`script_episode_id`, `deleted`),
    KEY `idx_script_asset_binding_project_episode` (`project_id`, `episode_number`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='剧本资产预匹配结果';
